# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Logintodockerhub:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v2.1.0
        with:
          registry: registry-1.docker.io
          username: ${{secrets.DOCKERHUBUSERNAME}}
          password: ${{secrets.DOCKERHUBPASSWORD}}
          
	  Logintodockerhub:
	    runs-on: ubuntu-latest
	    environment: QA
	    steps:
	      - uses: actions/checkout@v3
	      - name: docker login
	        uses: docker/login-action@v2.1.0
	        with:
	          registry: registry-1.docker.io
	          username: ${{secrets.DOCKERHUBUSERNAME}}
	          password: ${{secrets.DOCKERHUBPASSWORD}}
